from __future__ import annotations

CONFIG_KEYS = {
    "LIBVIRT_URI",
    "BACKUP_PATH",
    "HOST_ID",
    "VM_BLACKLIST",
    "SYSTEMD_ON_CALENDAR",
    "BACKUP_REQUIRE_NFS_MOUNT",
    "BACKUP_REQUIRE_FSTAB_CONSISTENCY",
    "SPACE_MARGIN_PERCENT",
    "BACKUP_ESTIMATE_GB_PER_VM",
    "REQUIRE_ROOT",
    "COMMAND_TIMEOUT_SECONDS",
    "KOPIA_REPO_PATH",
    "KOPIA_PASSWORD_FILE",
    "KOPIA_CACHE_DIR",
    "KOPIA_PARALLELISM",
    "KOPIA_SPLITTER",
    "KOPIA_COMPRESSION",
    "KEEP_LATEST",
    "KEEP_HOURLY",
    "KEEP_DAILY",
    "KEEP_WEEKLY",
    "KEEP_MONTHLY",
    "KEEP_ANNUAL",
    "KOPIA_MAINTENANCE_INTERVAL",
    "KOPIA_VERIFY_INTERVAL",
}


DEFAULTS = {
    "LIBVIRT_URI": "qemu:///system",
    "BACKUP_PATH": "",
    "HOST_ID": "",
    "VM_BLACKLIST": "",
    "SYSTEMD_ON_CALENDAR": "*-*-* 02:30:00",
    "BACKUP_REQUIRE_NFS_MOUNT": "true",
    "BACKUP_REQUIRE_FSTAB_CONSISTENCY": "true",
    "SPACE_MARGIN_PERCENT": "20",
    "BACKUP_ESTIMATE_GB_PER_VM": "1",
    "REQUIRE_ROOT": "true",
    "COMMAND_TIMEOUT_SECONDS": "86400",
    # Kopia-engine keys (read by the kopia_* modules in phase 1; consumed by
    # backup / restore / retention from phase 3 onward).
    "KOPIA_REPO_PATH": "",
    "KOPIA_PASSWORD_FILE": "/etc/libvirt-backup-system/kopia.pw",
    "KOPIA_CACHE_DIR": "/var/cache/libvirt-backup-system/kopia",
    "KOPIA_PARALLELISM": "4",
    "KOPIA_SPLITTER": "FIXED-4M",
    "KOPIA_COMPRESSION": "zstd-fastest",
    "KEEP_LATEST": "8",
    "KEEP_HOURLY": "24",
    "KEEP_DAILY": "365",
    "KEEP_WEEKLY": "0",
    "KEEP_MONTHLY": "0",
    "KEEP_ANNUAL": "0",
    "KOPIA_MAINTENANCE_INTERVAL": "24h",
    "KOPIA_VERIFY_INTERVAL": "7d",
}


COMMENTED_ENV_KEYS = {
    "LIBVIRT_URI",
    "HOST_ID",
    "VM_BLACKLIST",
    "SYSTEMD_ON_CALENDAR",
    "BACKUP_REQUIRE_NFS_MOUNT",
    "BACKUP_REQUIRE_FSTAB_CONSISTENCY",
    "SPACE_MARGIN_PERCENT",
    "BACKUP_ESTIMATE_GB_PER_VM",
    "REQUIRE_ROOT",
    "COMMAND_TIMEOUT_SECONDS",
    "KOPIA_REPO_PATH",
    "KOPIA_PASSWORD_FILE",
    "KOPIA_CACHE_DIR",
    "KOPIA_PARALLELISM",
    "KOPIA_SPLITTER",
    "KOPIA_COMPRESSION",
    "KEEP_LATEST",
    "KEEP_HOURLY",
    "KEEP_DAILY",
    "KEEP_WEEKLY",
    "KEEP_MONTHLY",
    "KEEP_ANNUAL",
    "KOPIA_MAINTENANCE_INTERVAL",
    "KOPIA_VERIFY_INTERVAL",
}


ENV_TEMPLATE: tuple[str | None, ...] = (
    "# libvirt-backup-system environment file",
    "#",
    "# Installed path:",
    "#   /etc/libvirt-backup-system/libvirt-backup.env",
    "#",
    "# Values in the real process environment override values in this file.",
    "# Booleans accept (case-insensitive): 1, true, yes, on as true;",
    "# 0, false, no, off as false. Any other value is rejected by preflight.",
    None,
    "# Libvirt connection used by virsh for VM discovery and state checks.",
    "LIBVIRT_URI",
    None,
    "# Backup root. The per-host kopia repository is written under:",
    "#   BACKUP_PATH/<host-id>/kopia-repo/",
    "# One repo per host, sharing the same password file. Peer hosts' repos",
    "# live at sibling BACKUP_PATH/<other-host-id>/kopia-repo/ paths and are",
    "# discovered automatically for cross-host listing and restore.",
    "BACKUP_PATH",
    None,
    "# Require BACKUP_PATH to be a mounted filesystem, usually an NFS/QNAP mount.",
    "# Enabled by default so a missing mount fails preflight instead of silently",
    "# writing backups to the local disk. Set to false only for intentionally",
    "# local backup directories.",
    "BACKUP_REQUIRE_NFS_MOUNT",
    None,
    "# Require every node's /etc/fstab entry for the BACKUP_PATH mount to match",
    "# the entry recorded in the backup tree by the first node: same upstream",
    "# server (same IP/export), same filesystem type, same mount options. Also",
    "# verifies the live mount matches fstab. Mismatches fail preflight before",
    "# any backup is attempted. Enabled by default.",
    "# NOTE: if you change the NFS server address, update /etc/fstab on ALL",
    "# nodes, remount, and run ``push-config`` on one node to re-record the",
    "# shared entry.",
    "BACKUP_REQUIRE_FSTAB_CONSISTENCY",
    None,
    '# Backup host folder name. Empty means "use /etc/machine-id".',
    "# Scopes the per-host kopia repo: snapshots from this host land under",
    "# BACKUP_PATH/<HOST_ID>/kopia-repo/. Keep this stable: renaming HOST_ID",
    "# starts a fresh repo under a new folder and leaves the old data",
    "# untouched in the prior HOST_ID directory.",
    "HOST_ID",
    None,
    "# VM UUIDs to skip. Separate with spaces or commas.",
    "# Use ``virsh domuuid <vm-name>`` to look up a VM's UUID.",
    "VM_BLACKLIST",
    None,
    "# systemd OnCalendar value used when the backup timer is installed.",
    "# Run start after changing this so the backup timer is refreshed and reloaded.",
    "SYSTEMD_ON_CALENDAR",
    None,
    "# Extra free-space margin added to preflight's backup size estimate.",
    "SPACE_MARGIN_PERCENT",
    None,
    "# Per-VM backup size estimate used by preflight space checks, in GB.",
    "# Used only as a fallback when disk introspection (virsh / qemu-img) fails.",
    "BACKUP_ESTIMATE_GB_PER_VM",
    None,
    "# Require preflight and run commands to execute as root.",
    "REQUIRE_ROOT",
    None,
    "# Timeout for external commands, in seconds.",
    "COMMAND_TIMEOUT_SECONDS",
    None,
    "# Kopia repo location. Empty means BACKUP_PATH/<HOST_ID>/kopia-repo/",
    "# (the convention). If set, it MUST still equal that discoverable path",
    "# so peer listing and restore can find every host repo.",
    "KOPIA_REPO_PATH",
    None,
    "# Path to the shared kopia password file (mode 600, root-owned).",
    "# Written by ``install`` and rotated by ``change-password``. Lose this",
    "# file on every host and the repos become unreadable.",
    "KOPIA_PASSWORD_FILE",
    None,
    "# Local on-disk cache for kopia chunk metadata. Speeds up subsequent",
    "# operations against the same repo. Can be deleted at any time;",
    "# kopia rebuilds it on demand.",
    "KOPIA_CACHE_DIR",
    None,
    "# Passed to ``kopia snapshot create --parallel``. Higher values trade",
    "# CPU and read bandwidth for shorter per-VM backup windows; lower",
    "# values reduce contention with the running VMs.",
    "KOPIA_PARALLELISM",
    None,
    "# Repo splitter (chunker). Fixed-size is the correct choice for opaque",
    "# block streams (raw disk images coming out of nbdcopy). Change only",
    "# with a clean cutover; mixing splitters in one repo defeats dedup.",
    "KOPIA_SPLITTER",
    None,
    "# Repo-wide compression. Applied via the global kopia policy on start.",
    "KOPIA_COMPRESSION",
    None,
    "# Retention policy mapped onto ``kopia policy set --global --keep-*``.",
    "# Defaults keep the latest 8 snapshots plus hourly points for 24h",
    "# and daily points for one year.",
    "# The kopia maintenance timer prunes expired snapshots in the background;",
    "# the backup loop itself does not perform pruning.",
    "KEEP_LATEST",
    "KEEP_HOURLY",
    "KEEP_DAILY",
    "KEEP_WEEKLY",
    "KEEP_MONTHLY",
    "KEEP_ANNUAL",
    None,
    "# Cadence for ``kopia maintenance run`` against the local repo. Daily",
    "# quick maintenance, weekly full maintenance. No global owner: each",
    "# host maintains its own repo.",
    "KOPIA_MAINTENANCE_INTERVAL",
    None,
    "# Cadence for ``libvirt-backup-system verify`` against the local repo.",
    "# Cross-host verify is opt-in via",
    "# ``libvirt-backup-system verify --include-hosts=...`` and is not",
    "# scheduled by default.",
    "KOPIA_VERIFY_INTERVAL",
)
